Yuzhong timetable
AY2122S2-CS2113T-T09-1/tp pull request #153
Opened 2022-04-09 09:35 UTC by yuzhongng

Add java doc to the various Timetable class methods.

Add J-unit test for TimetableParser class.

2022-04-09 12:15 UTC, jltha requested changes

2022-04-09 12:15 UTC, jltha commented on src/main/java/seedu/sherpass/command/ShowCommand.java
> +     *
Violates convention. You can change to "Creates an object..."

2022-04-09 13:43 UTC, jltha commented on src/main/java/seedu/sherpass/command/ShowCommand.java
> +     * Creates and object of ShowCommand type.
Can remove the 'd' in 'and'

2022-04-09 13:49 UTC, laiisaac approved these changes

2022-04-09 13:49 UTC, jltha approved these changes

2022-04-10 05:55 UTC, thedarie approved these changes

2022-04-10 05:55 UTC, merged