Branch-UI-related-features
AY2122S2-CS2113T-T09-1/tp pull request #30
Opened 2022-03-09 14:38 UTC by jltha

2022-03-10 00:51 UTC, laiisaac approved these changes

2022-03-10 03:50 UTC, BradenTeo requested changes
Requested some code quality changes

2022-03-10 03:50 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Parser.java
> +            + HELP_MESSAGE_SPECIFIC_COMMAND);
I think the change needs to be reverted. For code quality.

2022-03-10 03:50 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Parser.java
> +            + "*Enter 'No' to skip the adding of this task*");
Can revert here too.

2022-03-10 03:50 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Parser.java
> +                || input.trim().equalsIgnoreCase("Yes")) {
Here too.

2022-03-10 03:50 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Parser.java
> +                || input.trim().equalsIgnoreCase("No")) {
I think for the rest of this class can revert all the similar changes.

2022-03-10 03:50 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Parser.java
> +                + "Please re-enter a valid default timer input");
Do add 8 spacings here. Can do the same for the rest of the file too.

2022-03-10 03:50 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Ui.java
> +        + "                       |_|";
Can maybe use a different colour here:
Maybe like:
```java
    public static final String ANSI_PURPLE = "\u001B[35m";
    public static final String ANSI_RESET = "\u001B[0m";
    public static final String ALEXIS_ICON =
            ANSI_PURPLE
            + "  ____  _\n"
            + " / ___|| |__   ___ _ __ _ __   __ _ ___ ___\n"
            + " \\___ \\| '_ \\ / _ \\ '__| '_ \\ / _` / __/ __|\n"
            + "  ___) | | | |  __/ |  | |_) | (_| \\__ \\__ \\\n"
            + " |____/|_| |_|\\___|_|  | .__/ \\__,_|___/___/\n"
            + "                       |_|" 
            + ANSI_RESET;
```
This website is useful: [ASC11 art](https://patorjk.com/software/taag/#p=testall&f=Graffiti&t=Sherpass)

2022-03-10 03:59 UTC, jltha commented on src/main/java/seedu/sherpass/utills/Parser.java
> +                + "Please re-enter a valid default timer input");
For which line do u mean? For the default branch, adding 8 spaces will throw a checkstyle error.

2022-03-10 04:00 UTC, jltha commented on src/main/java/seedu/sherpass/utills/Parser.java
> +            + HELP_MESSAGE_SPECIFIC_COMMAND);
This was part of the import code. What do u mean by revert?

2022-03-10 04:04 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Parser.java
> +                + "Please re-enter a valid default timer input");
Should we ask prof about this? From what I remember, the correct way was to leave 8 spaces.

2022-03-10 04:04 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Parser.java
> +            + HELP_MESSAGE_SPECIFIC_COMMAND);
Was referring to the 8 spaces

2022-03-10 04:06 UTC, jltha commented on src/main/java/seedu/sherpass/utills/Ui.java
> +        + "                       |_|";
woah cool cool, I'll try the diff colours

2022-03-11 02:39 UTC, thedarie approved these changes

2022-03-11 04:43 UTC, BradenTeo commented on src/main/java/seedu/sherpass/utills/Parser.java
> +                + "Please re-enter a valid default timer input");
I'll approve the PR first and we can edit the code quality afterward.

2022-03-11 04:45 UTC, BradenTeo approved these changes
We'll edit the code quality afterward once prof gets back to us.

2022-03-11 04:46 UTC, merged