Isaac lai study session
AY2122S2-CS2113T-T09-1/tp pull request #36
Opened 2022-03-12 16:54 UTC by laiisaac

Implement start, stop, pause function of the study timer.

Implements #23

2022-03-12 17:04 UTC, thedarie requested changes

2022-03-12 17:04 UTC, thedarie commented on src/main/java/seedu/sherpass/util/Timer.java
> +import static seedu.sherpass.constant.Timer.*;
try to use explicit imports

2022-03-12 17:04 UTC, thedarie commented on src/main/java/seedu/sherpass/util/Parser.java
> +import static seedu.sherpass.constant.Message.*;
think your IDE caused this, perhaps can revert back?

2022-03-12 17:10 UTC, thedarie commented on src/main/java/seedu/sherpass/util/Timer.java
> +            }
maybe add in an error message here

2022-03-12 17:20 UTC, laiisaac commented on src/main/java/seedu/sherpass/util/Parser.java
> +import static seedu.sherpass.constant.Message.*;
Yup, changed all the import *.

2022-03-12 17:26 UTC, laiisaac commented on src/main/java/seedu/sherpass/util/Timer.java
> +            }
This is an exception where the timer thread is interrupted (stopped e,g, when user manually stops the timer) so that the program will keep running. I added a return statement to satisfy the checkstyle error since we will not be printing an error message for the exception.

2022-03-12 17:26 UTC, laiisaac commented on src/main/java/seedu/sherpass/util/Parser.java
> +import static seedu.sherpass.constant.Message.*;
Will be trying to fix the remaining checkstyle errors

2022-03-12 19:41 UTC, jltha requested changes

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/duke/Timer.java
> +                }
Once you've finalised the logic of your code, try refactoring out more code to avoid an arrow-style code.

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/duke/SherpassTimer.java
> +
Try abstracting into smaller methods to improve code quality for this method.

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/sherpass/constant/Timer.java
> +public class Timer {
Maybe can rename the class to TimerConstant or TimerMessage for better clarity.

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/sherpass/command/StudyCommand.java
> +            }
This can be extracted into a separate public method in SherpassTimer Class, something like SherpassTimer.reset().

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +                }
Same issue for this, can extract out.

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +            }
Same issue here as described previously. Reason being that the purpose of parseStudyMode is simply to parse the select the Mode that the user has chosen, other logic handling will be taken care off by possibly other classes like SherpassTimer.

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +            }
Same situation as described above.

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/sherpass/command/StudyCommand.java
> +                + "For testing purposes, you can use a 30s timer with option 0.\n"
I'm thinking that this entire message that is supposed to be printed can be extracted and pasted in your Timer class, the one where you stored the messages for timer methods. Helps reduce the LoC in this method. This message will then be substituted as a constant in this method.

2022-03-12 19:41 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +            return DEFAULT_TIMER_ZERO;
Ohh? Is this a new default timer mode?

2022-03-12 19:43 UTC, jltha requested changes
Overall looks good, just need to work on the code structuring to follow design principles (from this week's topic) and coding standards.

2022-03-13 03:13 UTC, thedarie approved these changes

2022-03-13 04:51 UTC, yuzhongng approved these changes

2022-03-14 05:31 UTC, laiisaac commented on src/main/java/seedu/duke/SherpassTimer.java
> +
Yes, will work on refactoring the code for readability, then improving the UI if time permits

2022-03-14 06:36 UTC, laiisaac commented on src/main/java/seedu/sherpass/util/Parser.java
> +            return DEFAULT_TIMER_ZERO;
Yes, for testing purposes we have a short timer to see what happens when the timer ends naturally.

2022-03-14 07:10 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +            return DEFAULT_TIMER_ZERO;
In that case, maybe can just use /custom instead of a default timer, since the implementation is still the same.

2022-03-14 07:40 UTC, jltha requested changes

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +            return;
no need add this here, can throw InterruptedException in the method name.

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +                hasTimeLeft = false;
perhaps can extract this out to comply with SLAP.

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +            timeLeft -= 1;
May I know what this line does?

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/command/StudyCommand.java
> +        TimerLogic timerLogic = new TimerLogic(ui);
For lines 16 to 22, I think we can extract the message out and replace it with a constant. Then you can extract those and paste it inside the timerLogic.enterStudyMode() method.

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +            startTimer(parsedInput);
Should it be `TimerLogic.StartTimer` instead? Same for the methods that are called in parseTimerInput.

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +                ui.showToUser(minutesLeft + " minutes left.");
maybe original condition can be `if (timeLeft > ONE_MINUTE && timeLeft % ONE_MINUTE == 0)

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +            }
Then just before this statement, you can return the function, so no need the else.

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/TimerLogic.java
> +                leaveStudyMode();
can add a return after leaveStudyMode(), here, then afterwards you just need to add a `if(userInput.contains("start") && !isTimerRunning)`

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/TimerLogic.java
> +            ui.showToUser("You already have a timer running!");
same situation as described above to minimise too usages of if else and use more guard clauses.

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/TimerLogic.java
> +        } else {
So theoretically speaking there should be no else if you use guard clause.

2022-03-14 07:40 UTC, jltha commented on src/main/java/seedu/sherpass/util/TimerLogic.java
> +                timer.setDuration(duration);
Is this method part of the Thread class?

2022-03-14 07:41 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +            timeLeft -= 1;
line 45, for timerLeft = -1, if not maybe can use something like reset();?

2022-03-14 07:52 UTC, jltha requested changes

2022-03-14 07:52 UTC, jltha commented on src/main/java/seedu/sherpass/command/StudyCommand.java
>                  + "Welcome back to the main session! How can I help you?");
Can add to timerLogic.leaveStudyMode();

2022-03-14 07:52 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +            startTimer(parsedInput);
Can use that instead of importing the public methods one by one. Then just import TimerLogic Class.

2022-03-14 07:52 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +    public void resumeTimer() {
can rename to resume

2022-03-14 07:52 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +    public void pauseTimer() {
can rename to `pause`. It'll be confusing since there's another method with the same name.

2022-03-14 07:52 UTC, jltha commented on src/main/java/seedu/sherpass/util/TimerLogic.java
> +        }
Over here can put the printing of leaveStudyMode message which was in execute method of StudyCommand.

2022-03-14 07:55 UTC, jltha requested changes

2022-03-14 07:55 UTC, jltha commented on src/main/java/seedu/sherpass/util/Timer.java
> +            return;
Is this the same as pausing the timer? If so, do you want to put the pauseTimer() method here?

2022-03-14 09:47 UTC, jltha commented on src/main/java/seedu/sherpass/util/TimerLogic.java
> +            if (validDuration(duration)) {
I think u can revert back to original for here. If not, perhaps can rename to `isValidDuration`

2022-03-14 10:05 UTC, laiisaac commented on src/main/java/seedu/sherpass/command/StudyCommand.java
>                  + "Welcome back to the main session! How can I help you?");
Added in the next commit

2022-03-14 12:18 UTC, jltha commented on src/main/java/seedu/sherpass/util/TimerLogic.java
> +        if (validDuration(duration)) {
good to rename method name to `isValidDuration()`

2022-03-14 13:20 UTC, jltha approved these changes

2022-03-14 13:20 UTC, merged