Braden add, edit, delete, mark/unmark, list tasks
AY2122S2-CS2113T-T09-1/tp pull request #37
Opened 2022-03-13 06:39 UTC by BradenTeo

1. Implemented Add function.
2. Ensured Delete, Mark/Unmark, List functions still work
3. Removed all instances of Deadline and Event commands (code left from iP)
4. Fixed and tested saving and loading of sherpass.txt file
5. Implemented Edit function.

Fixes #21

2022-03-13 08:21 UTC, jltha requested changes
Good work on completing your part! Do come back and fix the changes when you're ready. :)

On a side note, please follow the commit message guidelines that was shared in the tele group. Your starting words **should be** a present tense verb with the first letter capitalised. Here's the (link)[https://se-education.org/guides/conventions/git.html] to the commit message conventions if you are unable to find it.

2022-03-13 08:21 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +            }
Avoid a nested if-else statement whenever possible. You can extract out the code or restructure the code logic.
E.g. After checking for condition in line 125, you don't need to add a else statement since you are returning a new AddCommand().

2022-03-13 08:21 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +
Same issue as explained above in line 125. Since there's no time in a task, you only need to check if can parse and then return localDate.format(DateTimeFormatter.ofPattern(DATE_FORMAT_WITHOUT_TIME)); 

Also, in the original iP code, this method checks if the time input is valid, before checking for valid date format in checkCorrectDateFormat(). If we don't intend to add a time, you can remove this and use the checkCorrectDateFormat method.

2022-03-13 08:21 UTC, jltha commented on src/main/java/seedu/sherpass/task/Task.java
> +        }
Same issue as explain in the previous commit. You can use e.g.

```
If (condition1) {
    return variable1;
}

if (condition2) {
    return variable2;
}

return variable3;
```

Having the else statements is unnecessary since you are returning an output.

2022-03-13 08:50 UTC, thedarie requested changes

2022-03-13 08:50 UTC, thedarie commented on src/main/java/seedu/sherpass/exception/WrongEditInfoFormat.java
> +}
maybe rename it to WrongEditInfoFormatException

2022-03-13 09:25 UTC, jltha commented on src/main/java/seedu/sherpass/exception/WrongEditInfoFormat.java
> +}
perhaps can just stick to InvalidInputException, since it also falls under this category of wrong input format/incorrect input content

2022-03-13 09:27 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +        }
Will need to change code structure, some parts are duplicate and need not be repeated

2022-03-13 09:54 UTC, yuzhongng approved these changes

2022-03-13 09:54 UTC, yuzhongng commented on src/main/java/seedu/sherpass/task/Task.java
>      }
Maybe you can overload the constructor to include optional byDate and optional remindDate.
If I have a task with no date specified. I can just call the Task constructor with the description itself.
If I have a task with a byDate specified, I can call the Task constructor with the description and the byDate together. Then you do not need to pass a null value to byDate if the task has no date specified to it in the parser class.

2022-03-13 09:54 UTC, yuzhongng commented on src/main/java/seedu/sherpass/task/Task.java
> +                    + " (by: " + this.byDate + ") (reminder on: " + this.remindDate + ")";
Maybe you can try returning String.format() method for easier readability. The method String.format() will have the string representation put together and the variable separated out.

2022-03-13 09:54 UTC, yuzhongng commented on src/main/java/seedu/sherpass/task/TaskList.java
> +    public void addTask(String taskDescription, String taskByDate, String taskRemindDate) {
You can overload the method too if you overload the task constructor.

2022-03-13 09:54 UTC, yuzhongng commented on src/main/java/seedu/sherpass/util/Parser.java
> +                }
Here is what I meant when you can overload the task. You do need to pass empty_string here anymore.

2022-03-13 09:54 UTC, yuzhongng commented on src/main/java/seedu/sherpass/util/Parser.java
> +                    + "(The task_description and task_due_date is left out here)");
Maybe you can try abstracting the string representation here to a constant.

2022-03-14 06:58 UTC, BradenTeo commented on src/main/java/seedu/sherpass/task/Deadline.java
> +*/
I've deleted this file already. Did you look at the [files changed](https://github.com/AY2122S2-CS2113T-T09-1/tp/pull/37/files) to review?

2022-03-14 07:00 UTC, BradenTeo commented on src/main/java/seedu/sherpass/task/Add.java
> +public class Add extends Task {
This class should not be showing up. I deleted it midway through my coding.

2022-03-14 07:10 UTC, BradenTeo commented on src/main/java/seedu/sherpass/task/Task.java
> +        }
Ok, will change it, thanks.

2022-03-14 07:15 UTC, BradenTeo commented on src/main/java/seedu/sherpass/util/Parser.java
> +            }
Thanks for pointing this out.

2022-03-14 07:32 UTC, BradenTeo commented on src/main/java/seedu/sherpass/util/Parser.java
> +
I'm not sure what you mean by this section having the same issue as line 125, since there are no `else` blocks here. 

For your 2nd point, do you mind giving an example on how to implement it?

2022-03-14 07:37 UTC, BradenTeo commented on src/main/java/seedu/sherpass/exception/WrongEditInfoFormat.java
> +}
Got it, will change it to WrongEditInfoFormatException.
@jltha I have a different exception message for this exception so I won't merge it with `InvalidInputException`

2022-03-14 07:44 UTC, BradenTeo commented on src/main/java/seedu/sherpass/util/Parser.java
> +        }
Sure, I'll refactor this. Thanks for pointing it out.

2022-03-14 07:58 UTC, jltha commented on src/main/java/seedu/sherpass/task/Add.java
> +public class Add extends Task {
ok will take a look. I probably missed it while reading the changes.

2022-03-14 08:10 UTC, BradenTeo commented on src/main/java/seedu/sherpass/task/Task.java
>      }
I'm not really sure how to implement this other than using different classes for each type of task (which would cause many complications when trying to implement the `edit` function). 

Not really sure if it's possible to override ~~overload~~ attributes in the same class.

2022-03-14 08:11 UTC, jltha requested changes

2022-03-14 08:11 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +
You can ignore the first point, its just a style preference, yours is much clearer.

For the second point, I meant that that is no need to have this method since there was already checkCorrectDateFormat method in it. They both work the same way. If you want to, u can delete checkCorrectDateFormat method and replaceline 213 with 

```
if (isParseSaveFile) {
                throw new InvalidInputException();
            }
            return confirmInvalidDateFormat();
```

But I think we'll put this on hold for now. Let's decide in the team meeting later on the usage of time along with date, since we have a /do command, maybe user wants to be reminded to do the item when it is a specific time or smt.

2022-03-14 08:24 UTC, BradenTeo commented on src/main/java/seedu/sherpass/util/Parser.java
> +    }
I see... I'll delete this method, thanks.
`NumberFormatException` is present in the method above.

2022-03-14 08:31 UTC, BradenTeo commented on src/main/java/seedu/sherpass/util/Parser.java
> +        }
I see. I'll implement this and you can check it later.

2022-03-14 08:43 UTC, BradenTeo commented
Oops I'll take note of my commit messages from now on

2022-03-14 10:06 UTC, yuzhongng commented on src/main/java/seedu/sherpass/task/Task.java
>      }
For eg. 
Task(String description) { }
Task(String description, String byDate) { }
Task(String description, String byDate, reminidDate) { }

Edit function would override description. The date portion would be more troublesome as you need to check whether date is null. But the edit function should probably be implemented in the same way as when you are using 1 constructor

2022-03-14 13:41 UTC, laiisaac requested changes

2022-03-14 13:41 UTC, laiisaac commented on src/main/java/seedu/sherpass/command/AddCommand.java
> +import seedu.sherpass.exception.InvalidInputException;
Might be a small nit-pick but maybe could group the imports which are related together (util, exception) and perhaps add a line between groups.

2022-03-14 13:41 UTC, laiisaac commented on src/main/java/seedu/sherpass/task/Task.java
>      }
Just to pen down what we discussed during the meeting - perhaps we can add a method in Parser to parse the parameters (e.g. if theres no deadline then we set it to null) and then pass all the parameters to the task constructor.

2022-03-15 02:11 UTC, thedarie approved these changes

2022-03-15 05:15 UTC, laiisaac approved these changes

2022-03-15 05:16 UTC, jltha approved these changes
To edit code structure and logic in the enhancement or next iteration

2022-03-15 05:17 UTC, merged

2022-03-15 06:27 UTC, yuzhongng commented on src/main/java/seedu/sherpass/task/Task.java
>      }
We could give a default value to byDate and remindDate outside of the constructor. So we do not need to assign a value to byDate or remindDate when it is not called in the constructor. But I agreed with you that you have to initialize 3 constructors which may be troublesome to read.