Daryl recurring task
AY2122S2-CS2113T-T09-1/tp pull request #55
Opened 2022-03-21 09:57 UTC by thedarie

Added support for adding and editing recurring tasks.

1. new command 'addrecurring','editrecurring'
2. update storage class to load and write recurring tasks
3. changed LocalDate to LocalDateTime

2022-03-21 14:55 UTC, jltha requested changes

2022-03-21 14:55 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
>              return new AddCommand(filteredTaskContent[0], taskList, byDate, doOnDate);
Need to replace magic literals

2022-03-22 14:17 UTC, yuzhongng approved these changes

2022-03-24 10:53 UTC, jltha reviewed
Thanks for putting in the tremendous effort for this feature! I feel that there might be a better way to encapsulate the feature we want to implement, do take a look at what I mentioned in the tele group and let me know what you think.

2022-03-24 10:53 UTC, jltha commented on src/main/java/seedu/sherpass/command/AddRecurringCommand.java
> +        int identifier = taskList.generateIdentifier();
For the identifier, I was thinking that there's no need to generate a random number at the start. Simply sort the array first using a comparator, then call another method which loops through the array. Every task will then have its index set to the array index + 1.

2022-03-24 10:53 UTC, jltha commented on src/main/java/seedu/sherpass/util/Reminder.java
> +public class Reminder {
Not sure if this is needed since the timetable will reflect the tasks to the user

2022-03-24 10:54 UTC, jltha commented on src/main/java/seedu/sherpass/command/AddRecurringCommand.java
> +        int identifier = taskList.generateIdentifier();
These would fall under TaskList class to sort the array and assign the identifiers/ task list index.

2022-03-24 10:57 UTC, thedarie commented on src/main/java/seedu/sherpass/util/Reminder.java
> +public class Reminder {
oops im not sure why this class is still here, will remove it

2022-03-24 10:59 UTC, thedarie commented on src/main/java/seedu/sherpass/command/AddRecurringCommand.java
> +        int identifier = taskList.generateIdentifier();
the identifier is used to identify which tasks are of the same 'recurrence' so if we want to delete all future recurrence of a task its easy to identify them.
for that reason, each 'recurrence' should have a unique identifier and i feel that if we use index based, things can get very ugly when user constantly add and delete tasks

2022-03-24 13:08 UTC, jltha commented on src/main/java/seedu/sherpass/util/Parser.java
> +        return splitArguments[0];
To add constant for this magic literal

2022-03-24 13:08 UTC, jltha commented on src/main/java/seedu/sherpass/command/AddRecurringCommand.java
> +
can shift to commonLogic. Also, a more suitable name can be taskLogic since this class handles task related calculation.

2022-03-24 13:08 UTC, jltha commented on src/main/java/seedu/sherpass/command/DeleteRecurringCommand.java
> +
Same for here.

2022-03-24 13:08 UTC, jltha commented on src/main/java/seedu/sherpass/command/EditRecurringCommand.java
> +        return EMPTY_STRING;
Can shift this to commonLogic

2022-03-24 13:31 UTC, thedarie commented on src/main/java/seedu/sherpass/command/AddRecurringCommand.java
> +
thanks for the good suggestion, will change accordingly

2022-03-24 13:42 UTC, thedarie commented on src/main/java/seedu/sherpass/util/Parser.java
> +        return splitArguments[0];
ok, will add it in the next commit

2022-03-24 13:54 UTC, jltha commented on src/main/java/seedu/sherpass/command/EditRecurringCommand.java
>      public void execute(TaskList taskList, Ui ui, Storage storage) {
Most of the code can be brought over to taskLogic, since this actually handles checking and setting of values to prepare to add the task to tasklist

2022-03-24 13:54 UTC, jltha commented on src/main/java/seedu/sherpass/command/DeleteRecurringCommand.java
> +        String error = TaskLogic.checkValidDeleteArgument(taskList, index);
lines 27 to 43 can be brought over to taskLogic since this is the logic implementation of preparing the task to be added to task list

2022-03-24 13:54 UTC, jltha commented on src/main/java/seedu/sherpass/command/AddRecurringCommand.java
> +        String error = TaskLogic.checkValidAddArgument(taskDescription, doOnStartDateTime, doOnEndDateTime, frequency);
Lines 40 to  61 can be part of taskLogic

2022-03-25 08:17 UTC, thedarie commented on src/main/java/seedu/sherpass/command/AddRecurringCommand.java
> +        String error = TaskLogic.checkValidAddArgument(taskDescription, doOnStartDateTime, doOnEndDateTime, frequency);
I agreed that for adding, most of the preparation work can be done in TaskLogic, however for editing and deletion I think it would be better to revise this another time because it might also make sense to involve TaskList class in it as well. (getting list of indexes to be edited, etc)

For now I think a more pressing issue is to work on the non-recurring commands and come back to this at a later time

2022-03-25 08:44 UTC, laiisaac approved these changes

2022-03-25 10:18 UTC, jltha approved these changes

2022-03-25 10:18 UTC, merged