Daryl refactor
AY2122S2-CS2113T-T09-1/tp pull request #96
Opened 2022-03-31 14:30 UTC by thedarie

1. Remove Tasklist's dependency on Ui - Theres still some print methods used by Timetable that I daren't touch
2. Remove Storage's dependency on Ui
3. Refactor certain parts of TaskParser
4. Modify logic of editing commands - Tasks to be edited are removed first then added to check for clashes
5. Modify logic of adding commands - Single task is added the 'recurring' way but only 1 iteration
6. Created new method in Ui to take in Y/N responses and return true/false respectively
7. Add value 'SINGLE' into Frequency to denote non recurring tasks
8. Add TimeClashException which is thrown when clashing tasks are detected

2022-03-31 14:52 UTC, laiisaac approved these changes

2022-03-31 15:12 UTC, jltha requested changes
Some small stuff I noticed in the code base, but overall nice work on the refactoring!

2022-03-31 15:12 UTC, jltha commented on src/main/java/seedu/sherpass/util/parser/TaskParser.java
> +        //}
Can remove this, since you did a try catch in prepareAdd method

2022-03-31 15:12 UTC, jltha commented on src/main/java/seedu/sherpass/task/TaskList.java
> +            tasks.removeIf(task -> task.getIdentifier() == identifier && task.getIndex() >= taskToBeRemoved.getIndex());
Does this remove the current task we want to edit as well? I'm slightly confused by the extra check for `task.getIndex() >= taskToBeRemoved.getIndex()`.

2022-03-31 15:16 UTC, thedarie commented on src/main/java/seedu/sherpass/command/EditCommand.java
> +        if (byDate != null && taskToEdit.getRepeatFrequency() != Frequency.SINGLE) {
yes right, was in a hurry and missed this thanks!

2022-03-31 15:17 UTC, thedarie commented on src/main/java/seedu/sherpass/task/TaskList.java
> +            tasks.removeIf(task -> task.getIdentifier() == identifier && task.getIndex() >= taskToBeRemoved.getIndex());
yes it does. we check the index cause we want to remove future occurrences as well, but not the past occurrences. 
checking by date instead of index should work the same way since the indexes are based on sorted order anyways

2022-03-31 15:19 UTC, thedarie commented on src/main/java/seedu/sherpass/command/EditCommand.java
> +        if (byDate != null && taskToEdit.getRepeatFrequency() != Frequency.SINGLE) {
wait i think you are looking at the wrong commit, this seems like an outdated version

2022-03-31 15:27 UTC, yuzhongng commented on src/main/java/seedu/sherpass/task/TaskList.java
> +            if (task.getDoOnStartDateTime().toLocalDate().isEqual(dateInput)) {
Here might have issue. If task getDoOnStartDateTime return a empty string. It will crash when it call toLocalDate. Thats why need to check if getDoOnStartDateTime is EmptyString or not.

2022-03-31 15:42 UTC, thedarie commented on src/main/java/seedu/sherpass/task/TaskList.java
> +            if (task.getDoOnStartDateTime().toLocalDate().isEqual(dateInput)) {
it should be fine since do date is a compulsory attribute for all tasks regardless of recurring / non recurring

2022-03-31 15:42 UTC, thedarie commented on src/main/java/seedu/sherpass/task/TaskList.java
> +            if (task.getDoOnStartDateTime().toLocalDate().isEqual(dateInput)) {
as for the second point im not entirely sure which functions are used by timetable so i think it's better if i leave it untouched

2022-03-31 15:48 UTC, jltha commented on src/main/java/seedu/sherpass/task/TaskList.java
> +            tasks.removeIf(task -> task.getIdentifier() == identifier && task.getIndex() >= taskToBeRemoved.getIndex());
In that case, we'll need to specify this in the UG, i.e. only future instances of recurring tasks will have its content changed along with the current edited task

2022-03-31 16:11 UTC, yuzhongng approved these changes

2022-04-01 03:42 UTC, thedarie commented on src/main/java/seedu/sherpass/task/TaskList.java
> +            tasks.removeIf(task -> task.getIdentifier() == identifier && task.getIndex() >= taskToBeRemoved.getIndex());
It's already specified under the 'Edit recurring tasks' section in the command guide

2022-04-01 05:34 UTC, jltha approved these changes

2022-04-01 05:34 UTC, merged